account/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('register/', register_view, name="register"),
    path('registerCareer/', register_view_career, name="registerCareer"),
    path('registerCareer2/', register_view_career2, name="registerCareer2"),
    path('registerUniv/', register_view_univ, name="registerUniv"),
    path('registerUniv2/', register_view_univ2, name="registerUniv2"),
    path('signupComplete/', signupComplete, name="signupComplete"),
    path('activate/<str:uidb64>/<str:token>', activate, name="activate"),
    path('profile/<str:id>', profile, name="profile"),
    path('<int:pk>/follow/',follow, name="follow"),
    path('<int:pk>/see_follower/',see_follower, name="see_follower"),
    path('<int:pk>/see_following/',see_following, name="see_following"),
    path('otherpage/<str:id>', otherpage, name="otherpage"),
    path('chaneInfo/', change_info, name="changeInfo"),
    path('withdraw/', withdraw, name="withdraw"),
    path('changePW/', change_password, name="changePW"),
    path('change/', change, name="change"),
    path('careerEdit/<str:id>', career_edit, name="careerEdit"),
    path('careerShow/', career_show, name="careerShow"),
    path('univEdit/<str:id>', university_edit, name="univEdit"),
    path('univShow/', university_show, name="univShow"),
    path('goChange/', go_change, name="goChange"),
]

post/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('<int:id>',detail,name="detail"), 
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('update/<str:id>', update, name="update"),
    path('delete/<str:id>', delete, name="delete"),
    path('detail/<str:id>', detail, name="detail"),
    path('detail/<str:post_id>/comment/create', comment_create, name="comment_create"),
    path('detail/<str:post_id>/comment/delete', comment_delete, name="comment_delete"),
    path('like/', likes, name="likes"),
]

sproject/urls.py
from django.contrib import admin
from django.urls import path, include
from post.views import home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('account/', include('account.urls')),
    path('post/', include('post.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
# Create your models here.

class CustomUser(AbstractUser):
    profile_image = models.ImageField(upload_to = "profile/", default = "profile/blank_profile_image.png")  #사진

    name = models.CharField(max_length=100)  #이름

    MAJOR_IN_SCHOOL_CHOICES = [ #전공 선택지 
        ('컴퓨터공학과', '컴퓨터공학과'), 
        ('기계시스템디자인공학과', '기계시스템디자인공학과'), 
        ('신소재공학과', '신소재공학과'), 
        ('화학공학과', '화학공학과'), 
        ('건설환경공학과', '건설환경공학과'), 
        ('전자전기공학부','전자전기공학부'), 
        ('산업데이터공학과', '산업데이터공학과'), 
        ('법학부', '법학부'), 
        ('뮤지컬전공', '뮤지컬전공'), 
        ('실용음악전공', '실용음악전공'), 
        ('건축학과', '건축학과'), 
        ('실내건축학과', '실내건축학과'), 
        ('도시공학과', '도시공학과'), 
        ('국어국문학과', '국어국문학과'), 
        ('영어영문학과', '영어영문학과'), 
        ('불어불문학과', '불어불문학과'), 
        ('독어독문학과', '독어독문학과'), 
        ('미술대학자율전공', '미술대학자율전공'), 
        ('예술학과', '예술학과'), 
        ('조소과', '조소과'), 
        ('회화과', '회화과'), 
        ('동양화가', '동양화가'), 
        ('판화과', '판화과'), 
        ('교육학과', '교육학과'), 
        ('국어교육과', '국어교육과'), 
        ('영어교육과', '영어교육과'), 
        ('수학교육과', '수학교육과'), 
        ('역사교육과', '역사교육과'), 
        ('시각디자인학과', '시각디자인학과'), 
        ('산업디자인학과', '산업디자인학과'), 
        ('도예유리과', '도예유리과'), 
        ('목조형가구학과', '목조형가구학과'), 
        ('금속조형디자인과', '금속조형디자인과'), 
        ('섬유미술패션디자인과', '섬유미술패션디자인과'), 
        ('경영학과', '경영학과'), 
        ('경제학과', '경제학과'), 
        ('서울캠퍼스자율전공', '서울캠퍼스자율전공'), 
        ('디자인경영융합학부', '디자인경영융합학부'), 
        ('디자인컨버전스학부', '디자인컨버전스학부'), 
        ('영상애니메이션학부', '영상애니메이션학부'), 
        ('게임소프트웨어공학전공', '게임소프트웨어공학전공'), 
        ('게임그래픽디자인전공', '게임그래픽디자인전공'), 
        ('과학기술대학자율전공', '과학기술대학자율전공'), 
        ('건축디자인과', '건축디자인과'), 
        ('건축공학과', '건축공학과'), 
        ('기계정보공학과', '기계정보공학과'), 
        ('조선해양공학과', '조선해양공학과'), 
        ('바이오화학공학과', '바이오화학공학과'), 
        ('나노신소재공학과', '나노신소재공학과'), 
        ('전자전기융합공학과', '전자전기융합공학과'), 
        ('소프트웨어융합공학과', '소프트웨어융합공학과'), 
        ('글로벌경영학과', '글로벌경영학과'), 
        ('금융보험학과', '금융보험학과'), 
        ('회계학과', '회계학과'), 
        ('광고홍보학부', '광고홍보학부'), 
        ('산업스포츠학과', '산업스포츠학과'), 
        ('세종캠퍼스자율전공', '세종캠퍼스자율전공') 
    ]

    major = models.CharField(  #전공
        max_length=30,
        choices=MAJOR_IN_SCHOOL_CHOICES,
        default='컴퓨터공학과',
    )

    STUDENT_NUM_CHOICES = [
        ('09', '09'),
        ('10', '10'),
        ('11', '11'),
        ('12', '12'),
        ('13', '13'),
        ('14', '14'),
        ('15', '15'),
        ('16', '16'),
        ('17', '17'),
        ('18', '18'),
        ('19', '19'),
        ('20', '20'),
        ('21', '21'),

    ]
    studentNum = models.CharField(
        max_length=10,
        choices=STUDENT_NUM_CHOICES,
        default=21
        )  #학번

    CAMPUS_CHOICES = [#캠퍼스 선택지
        ('서울캠퍼스', '서울캠퍼스'),
        ('세종캠퍼스', '세종캠퍼스'),
    ]

    campus = models.CharField(#캠퍼스
        max_length=50,
        choices=CAMPUS_CHOICES,
        default='서울캠퍼스'
    )

    schoolEmail = models.EmailField(max_length=100) #이메일
    email_auth = models.BooleanField(default=False) # 이메일 인증 여부

    #웹사이트
    websiteName = models.CharField(max_length=150, blank=True, null=True) #이름
    websiteURL = models.CharField(max_length=150, blank=True, null=True) #URL

    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings',blank=True)




class Career(models.Model):
	user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)
	company = models.CharField(max_length=50, blank=True, null=True) #회사
	title = models.CharField(max_length=50, blank=True, null=True) #직함
	CAREER_YEAR_START_CHOICES = [ #시작 연도 선택지
        ('2015', '2015'),
        ('2016', '2016'),
        ('2017', '2017'),
        ('2018', '2018'),
        ('2019', '2019'),
        ('2020', '2020'),
        ('2021', '2021'),
    ]
	careerYearStart = models.CharField( #시작연도
        max_length=10,
        choices=CAREER_YEAR_START_CHOICES,
        default='2021',
        blank=True, 
        null=True
    )
	CAREER_MONTH_START_CHOICES = [ #시작 월 선택지
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
        ('7', '7'),
        ('8', '8'),
        ('9', '9'),
        ('10', '10'),
        ('11', '11'),
        ('12', '12'),
    ]
	careerMonthStart = models.CharField( #시작 월
        max_length=3,
        choices=CAREER_MONTH_START_CHOICES,
        default='1',
        blank=True, 
        null=True
    )
	CAREER_YEAR_END_CHOICES = [ #종료년도 선택지
        ('2015', '2015'),
        ('2016', '2016'),
        ('2017', '2017'),
        ('2018', '2018'),
        ('2019', '2019'),
        ('2020', '2020'),
        ('2021', '2021'),
        ('재직중','재직중'),
    ]
	careerYearEnd = models.CharField( #종료년
        max_length=10,
        choices=CAREER_YEAR_END_CHOICES,
        default='2021',
        blank=True, 
        null=True
    )
	CAREER_MONTH_END_CHOICES = [ #종료 월 선택지
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
        ('7', '7'),
        ('8', '8'),
        ('9', '9'),
        ('10', '10'),
        ('11', '11'),
        ('12', '12'),
        (' ','재직중')
    ]
	careerMonthEnd = models.CharField( #종료 월 선택
        max_length=3,
        choices=CAREER_MONTH_END_CHOICES,
        default='1',
        blank=True, 
        null=True
    )




class Univ(models.Model):
	#대학생 활동
	user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True) 
	universityActivity = models.CharField(max_length=50, blank=True, null=True) #활동명
	universityTitle = models.CharField(max_length=50, blank=True, null=True) #직함
	UNIVERSITY_YEAR_START_CHOICES = [ #시작년도 선택지
        ('2015', '2015'),
        ('2016', '2016'),
        ('2017', '2017'),
        ('2018', '2018'),
        ('2019', '2019'),
        ('2020', '2020'),
        ('2021', '2021'),
    ]
	university_YearStart = models.CharField( #시작년도
        max_length=10,
        choices=UNIVERSITY_YEAR_START_CHOICES,
        default='2021',
        blank=True, 
        null=True
    )
	UNIVERSITY_MONTH_START_CHOICES = [ #시작월 선택지
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
        ('7', '7'),
        ('8', '8'),
        ('9', '9'),
        ('10', '10'),
        ('11', '11'),
        ('12', '12'),
    ]
	university_MonthStart = models.CharField( #시작 월
        max_length=3,
        choices=UNIVERSITY_MONTH_START_CHOICES,
        default='1',
        blank=True, 
        null=True
    )
	UNIVERSITY_YEAR_END_CHOICES = [#종료년도 선택지
        ('2015', '2015'),
        ('2016', '2016'),
        ('2017', '2017'),
        ('2018', '2018'),
        ('2019', '2019'),
        ('2020', '2020'),
        ('2021', '2021'),
        ('활동중','활동중'),
    ]
	university_YearEnd = models.CharField( #종료 년
        max_length=10,
        choices=UNIVERSITY_YEAR_END_CHOICES,
        default='2021',
        blank=True, 
        null=True
    )
	UNIVERSITY_MONTH_END_CHOICES = [ #종료 월 선택지
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
        ('7', '7'),
        ('8', '8'),
        ('9', '9'),
        ('10', '10'),
        ('11', '11'),
        ('12', '12'),
        (' ','활동중'),
    ]
	university_MonthEnd = models.CharField( #종료 월
        max_length=3,
        choices=UNIVERSITY_MONTH_END_CHOICES,
        default='1',
        blank=True, 
        null=True
    )
	

post/models.py
from django.db import models
from account.models import CustomUser

# Create your models here.
class Post(models.Model):
    CATEGORY_CHOICES = [ #카테고리 선택지
        ('management', '총무 및 사무'),
        ('business', '영업'),
        ('PerDepart', '인사'),
        ('customerC', '고객상담'),
        ('marketing', '마케팅'),
        ('trade', '유통 및 무역'),
        ('design', '디자인'),
        ('develop', '개발'),
        ('judicial', '법무 및 특허'),
        ('strategy', '전략 및 기획'),
        ('financial', '재무 및 회계'),
        ('sales', '구매 및 조달'),
        ('service', '서비스'),
        ('profession', '전문직'),
        ('medical', '의료 및 제약'),
        ('educ', '교육직'),
        ('construct', '건설 및 인테리어'),
        ('research', '연구 및 생산, 제조'),
        ('media', '미디어'),
        ('etc', '특수'),
    ]
    category = models.CharField(#카테고리
        max_length=50,
        choices=CATEGORY_CHOICES,
        default='develop',
    ) 
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    pub_date = models.DateTimeField()#올린 날짜
    body = models.TextField()# 내용
    hashtag = models.CharField(max_length=50) #해쉬태그
    image = models.ImageField(upload_to = "post/", blank=True, null=True)# 이미지
    link = models.CharField(max_length=100, blank=True, null=True)#링크
    
    like = models.ManyToManyField(CustomUser, related_name='likes',blank=True)

    def summary(self):
        return self.body[:100]


class Comment(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)
    post = models.ForeignKey(Post, null=True, on_delete=models.CASCADE)
    content = models.TextField(blank=True)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

account/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, UserCreationForm
from .models import CustomUser
from django import forms
from .models import Career, Univ



class RegisterForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password1', 'password2', 'profile_image', 'name', 'major', 'studentNum', 'campus', 'schoolEmail', 'websiteName', 'websiteURL']
        labels = {'username':'아이디','profile_image':'프로필 사진','name':'이름','major':'전공','studentNum':'학번','campus': '캠퍼스','schoolEmail':'학교 이메일','websiteName':'웹사이트 이름','websiteURL':'웹사이트 URL'}


class CareerForm(forms.ModelForm):
    class Meta:
        model = Career
        fields = ['company', 'title', 'careerYearStart', 'careerMonthStart', 'careerYearEnd', 'careerMonthEnd']
        labels = {'company': '회사', 'title':'직함', 'careerYearStart':'시작 연도', 'careerMonthStart':'시작 월', 'careerYearEnd':'종료 연도', 'careerMonthEnd':'종료 월'}

class UnivForm(forms.ModelForm):
    class Meta:
        model = Univ
        fields = ['universityActivity', 'universityTitle', 'university_YearStart', 'university_MonthStart', 'university_YearEnd', 'university_MonthEnd']
        labels = {'universityActivity': '대학생 활동', 'universityTitle':'직함', 'university_YearStart':'시작 연도', 'university_MonthStart':'시작 월', 'university_YearEnd':'종료 연도', 'university_MonthEnd':'종료 월'}

class ChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ['profile_image', 'name', 'major', 'studentNum', 'campus', 'schoolEmail', 'websiteName', 'websiteURL']
        labels = {'profile_image': '프로필 사진', 'name': '이름', 'major': '전공', 'studentNum': '학번', 'campus': '캠퍼스', 'schoolEmail': '학교 이메일', 'websiteName': '웹사이트 이름', 'websiteURL': '웹사이트 URL'}

account/templates/careerShow.html
{% extends 'base.html' %}

{% block content %}
<a href="{%url 'home'%}">홈화면</a>

{%for career in careers%}
<p><a href="{%url 'careerEdit' career.id%}">{{career.company}}  {{career.title}}</a></p>
<br>
<br>
{%endfor%}
{% endblock %}

account/templates/change.html
{% extends 'base.html' %}

{% block content %}
<style>
    a {
        font-size:13px;
        font-style:inherit;
        text-decoration-line: none;
        color : #5B9BD5;
    }
</style>

<div class = "container text-center">
    <h1 style="text-align: center;">수정 페이지</h1>
    <a href="{%url 'changeInfo'%}">&nbsp;회원정보 수정&nbsp;</a>
    <a href="{%url 'changePW'%}">&nbsp;비밀번호 수정&nbsp;</a>
    <a href="{%url 'registerCareer2' %}">&nbsp;커리어 추가&nbsp;</a>
    <a href="{%url 'registerUniv2' %}">&nbsp;대학생 활동 추가&nbsp;</a>
    <a href="{%url 'withdraw'%}">&nbsp;회원 탈퇴&nbsp;</a>
    <a href="{%url 'careerShow' %}">&nbsp;커리어 수정&nbsp;</a>
    <a href="{%url 'univShow' %}">&nbsp;대학생 활동 수정&nbsp;</a>
</div>
{% endblock %}

account/templates/changePassword.html
{% extends 'base.html' %}

{% block content %}
<style>
    h1 {font-size:25px; 
    font-weight:700; 
    padding: 5px 15px 15px;
    margin: 5px 15px 15px;
    text-align : center;}

    .signupbutton { 
    color: white; 
    font-size: 5px;
    border-radius: 5px;
    padding: 5px 7.5px; 
    margin: 2px 3px;
    border-style : none;
    text-align: center;
    }

    ul {
        text-align: left;
        display: inline-block;
    }
</style>

<div class = "container text-center">
    <h1 style="text-align: center">비밀번호 수정</h1>

    <form action="{% url 'changePW' %}" method="post">
        {%csrf_token%}
        {{form.as_p}}
        <button type="reset" class="signupbutton" style='background-color : red'> 취소 </button>
        <button type="submit" class="signupbutton" style='background-color: #5B9BD5'> 비밀번호 변경 </button>
    </form>
</div>
{% endblock %}

account/templates/changeUniv.html
{% extends 'base.html' %}

{% block content %}

<style>
    .changeunivbutton { 
        background-color : #5B9BD5; 
        color: white; 
        font-size: 7.5px;
        text-align : center;
        width:50px; height:30px;
        border-radius: 5px;
        border-style : none;
        text-align: center;
    }
</style>

<div class = "container text-center">
    <h1 style="text-align: center">대학생 활동 수정</h1>

    <form action="{% url 'univEdit' univ.id%}" method="post">
        {%csrf_token%}
        {{form.as_p}}
        <button type="submit" class='changeunivbutton'> 제출 </button> 
    </form>
</div>
{% endblock %}

account/templates/doubleCheck.html
{% extends 'base.html' %}

{% block content %}

<style>
    .doublecheckbutton { 
            background-color : #5B9BD5; 
        color: white; 
        font-size: 7.5px;
        text-align : center;
        width:50px; height:30px;
        border-radius: 5px;
        border-style : none;
        text-align: center;
    }
</style>
<div class = "container text-center">
    <br>
    <h3 style="text-align: center">아이디 및 비밀번호 재확인</h3>
    <br>
    <form action="{% url 'change' %}" method="post">
        {%csrf_token%}
        {{form.as_p}}
        <button type="submit" class="doublecheckbutton"> 로그인 </button> 
    </form>
</div>
{% endblock %}

account/templates/ifNotAuthenticated.html
{% extends 'base.html' %}

{% block content %}

<div class = "container text-center">
	<h1 style="text-align: center">로그인을 하셔야 합니다.</h1>
	<a href="{%url 'home'%}">홈 화면</a>
	<a href="{%url 'login'%}">로그인 화면</a>
	<a href="{%url 'register'%}">회원가입</a>
</div>

account/templates/invalid_password.html
{% extends 'base.html' %}

{% block content %}

<style>
    a {text-decoration-line:none;}

    #gosignupbutton { 
        color: white; 
        font-size: 5px;
        border-radius: 5px;
        padding: 5px 7.5px; 
        margin: 2px 3px;
        border-style : none;
        background-color: #5B9BD5;
        }
</style>

<div class = "container text-center">
    <br>
    <h3>비밀번호가 유효하지 않습니다. 다시 작성하시오.</h3>
    <br>
    <a href="{%url 'register'%}" id="gosignupbutton">회원가입으로 돌아가기</a>
</div>
{% endblock %} 

account/templates/profile.html
{% extends 'base.html' %}

{% block content %}
<head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
</head>

<style>
    html, body {
        margin: 0;
        height: 100%;
    }

    .custom-border {
        border : 2px solid rgba(91,155,213,0.5);
        padding : 20px 10px 10px 15px;
        border-width:2px;
        border-radius : 6px;     }

    .profile-image {
        width: 100px;
        height: 100px;
        object-fit: cover;
    }
    #text_post
    {
        overflow: hidden; text-overflow: ellipsis; 
        display: -webkit-box; 
        -webkit-line-clamp: 3; 
        -webkit-box-orient: vertical; 
        word-wrap:break-word;   }
    #id_category
        {
            font-size:11px;
            margin-bottom: 5px;
        }

    .feeling_a {
        background-color: #fff;
        border: 0px;
        color: #5B9BD5;
        font-size:13px;
        float:right;
        margin-left:5px;
    }

    .btn-normal {
        color: white; 
        background-color: #5B9BD5;
        font-size: 5px;
        border-radius: 5px;
        padding: 5px 7.5px; 
        margin: 2px 3px;
        border-style : none;
        text-align: center;
    }  
</style>


<div class="container h-150">
    <div class="row mb-3 p-3 custom-border">
        <img class="p-0 mb-2 profile-image" src="{{user.profile_image.url}}" alt="프로필 사진"><br>
        <div class="p-0  mb-2" style="font-size:20px">
            {{user.name}}({{user.major}}{{user.studentNum}})
            {% if request.user == user %}
            <a class="link-secondary" href="{% url 'change' %}"><i class="fas fa-user-edit"></i></a>
            {% endif %}
        </div>


        {% if request.user != user %}
        {% if request.user in follower_list %}
        <a href="{% url 'follow' user.id %}"><button class="btn btn-primary" style="float:right; font-size:13px;">팔로잉</button></a>
        {%else%}
        <a href="{% url 'follow' user.id %}"><button class="me-2 btn btn-secondary btn-sm" style="float:right; font-size:13px;">팔로우</button></a>
        {% endif %}
        {% endif %}
    
        <ul style="font-size:14px;">
        <div class="p-0">팔로워<a href="{% url 'see_follower' user.id %}"> {{follower_list | length}}</a>명</div>
        <div class="p-0">팔로잉<a href="{% url 'see_following' user.id %}"> {{following_list | length}}</a>명</div></a></ul>
    </div>
    <div class="row h-50">
        <div class="col-4 me-2 mh-100 overflow-auto custom-border"style="padding : 10px;">
            <div class="mt-2 p-1 custom-border"style="margin-bottom : 10px;">
                <span class="fw-bold" style="font-size:14px">경력</span>
                <ul class="mt-2" style="font-size:12px">
                    {% for career in career_list %}
                    {% if career.company %}
                    <li>{{career.company}} {{career.title}}
                        {{career.careerYearStart}}.{{career.careerMonthStart}}~{{career.careerYearEnd}}.{{career.careerMonthEnd}}
                    </li>
                    {% endif %}
                    {% endfor %}
                </ul>
            </div>
            <div class="mt-2 mb-2 p-1 custom-border"style="padding : 10px;">
                <span class="fw-bold"style="font-size:14px">대학생 활동 경력</span>
                <ul class="mt-2" style="font-size:12px">
                    {% for univ in univ_list %}
                    {% if univ.universityActivity %}
                    <li>{{univ.universityActivity}} {{univ.universityTitle}}
                        {{univ.university_YearStart}}.{{univ.university_MonthStart}}~{{univ.university_YearEnd}}.{{univ.university_MonthEnd}}
                    </li>
                    {% endif %}
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="col ms-2 mh-100 overflow-auto custom-border"style="padding : 10px;">
            <div class="mt-2 mb-2 fw-bold" style="font-size:14px">게시글</div>
            {% for post in post_list %}
            <div class="card my-2 custom-border">
                <div class="card-body">
                    {% if request.user == user %}
                    <div class="mb-1 d-flex justify-content-end">
                        <a href="{% url 'update' post.id %}"><button class="me-2 btn-normal">수정</button></a>
                        <a href="{% url 'delete' post.id %}"><button class="btn-normal" style='background-color : red'>삭제</button></a>
                    </div>
                    {% endif %}

                    <div style="font-size:12px; padding:10px; margin-bottom:5px;">
                        <span id= "text_post">{{post.body|linebreaks}}</span>
                    </div>
                    <p style="float:right; font-size:12px"><a href="{% url 'detail' post.id %}">자세히 보기</a></p>
                    <div id="id_category">
                        {{post.get_category_display}} <br></div>
                        <div id="id_category">
                        {{post.hashtag}} <br></div>

                    <a href="{%url 'detail' post.id%}"><button type="button" class="btn-normal" style="float:right; margin-left:5px;font-size:12px;">댓글달기</button></a>

                        <button id="{{post.id}}" class="feeling_a" onclick="post_like(this.id)">
                            {%if request.user in post.like.all%}
                            <!-- 로그인 한 유저가 좋아요를 누른 유저일때  -->
                            <i class="fas fa-heart heart {{post.id}}"></i>
                            {%else%}
                            <!-- 로그인 한 유저가 좋아요를 누른 유저가 아닐 때  -->
                            <i class="far fa-heart heart {{post.id}}"></i>
                            {%endif%}
                            <span class="like_count {{post.id}}">{{post.like.count}}</span>
                    </button>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<script type="text/javascript">
    function post_like(id) {
        $.ajax({
            url: "{%url 'likes'%}",
            data: {
                'post_id': id
            },
            dataType: "json",
            success: function (response) {
                $('.like_count' + '.' + id).html(response.like_count)
                if (response.message == "좋아요")
                {
                    $('.heart' + '.' + id).attr("class", "fas fa-heart heart " + id)
                } else if (response.message == "좋아요 취소")
                {
                    $('.heart' + '.' + id).attr("class", "far fa-heart heart " + id)
                }
            }
        })
    }
</script>
{% endblock %}

account/templates/signup.html
{% extends 'base.html' %}

{% block content %}
<style>
    h1 {font-size:25px; 
    font-weight:700; 
    padding: 5px 15px 15px;
    margin: 5px 15px 15px;
    text-align : center;}

    .signupbutton { 
    color: white; 
    font-size: 5px;
    border-radius: 5px;
    padding: 5px 7.5px; 
    margin: 2px 3px;
    border-style : none;
    }

    #id_profile_image {
        display: inline;
    }

    ul {
        text-align: left;
        display: inline-block;
    }
</style>

<div class = "container text-center">
<h1>회원가입</h1>

<form action="{% url 'register' %}" method="post" enctype="multipart/form-data">
    {%csrf_token%}
    {{form.as_p}}
    <button type="reset" class="signupbutton" style='background-color : red'> 취소 </button>
    <button type="submit" class="signupbutton" style='background-color: #5B9BD5'> 회원가입 </button>
</form>
</div>
{% endblock %} 

account/templates/wrongIDorpw2.html
{% extends 'base.html' %}
{% block content %}
<div class = "container" style="text-align : center;">
<h2><p style="text-align : center;">가입하지 않은 아이디이거나, 잘못된 비밀번호입니다.</p></h2>
<h2><a href="{%url 'home'%}" style="text-align : center;"> 홈 화면</a></h2>
</div>
{% endblock %}