post/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('<int:id>',detail,name="detail"), 
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('update/<str:id>', update, name="update"),
    path('delete/<str:id>', delete, name="delete"),
    path('detail/<str:id>', detail, name="detail"),
    path('detail/<str:post_id>/comment/create', comment_create, name="comment_create"),
    path('detail/<str:post_id>/comment/delete', comment_delete, name="comment_delete"),
    path('like/', likes, name="likes"),
]

sproject/urls.py
from django.contrib import admin
from django.urls import path, include
from post.views import home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('account/', include('account.urls')),
    path('post/', include('post.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

post/models.py
from django.db import models
from account.models import CustomUser

# Create your models here.
class Post(models.Model):
    CATEGORY_CHOICES = [ #카테고리 선택지
        ('management', '총무 및 사무'),
        ('business', '영업'),
        ('PerDepart', '인사'),
        ('customerC', '고객상담'),
        ('marketing', '마케팅'),
        ('trade', '유통 및 무역'),
        ('design', '디자인'),
        ('develop', '개발'),
        ('judicial', '법무 및 특허'),
        ('strategy', '전략 및 기획'),
        ('financial', '재무 및 회계'),
        ('sales', '구매 및 조달'),
        ('service', '서비스'),
        ('profession', '전문직'),
        ('medical', '의료 및 제약'),
        ('educ', '교육직'),
        ('construct', '건설 및 인테리어'),
        ('research', '연구 및 생산, 제조'),
        ('media', '미디어'),
        ('etc', '특수'),
    ]
    category = models.CharField(#카테고리
        max_length=50,
        choices=CATEGORY_CHOICES,
        default='develop',
    ) 
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    pub_date = models.DateTimeField()#올린 날짜
    body = models.TextField()# 내용
    hashtag = models.CharField(max_length=50) #해쉬태그
    image = models.ImageField(upload_to = "post/", blank=True, null=True)# 이미지
    link = models.CharField(max_length=100, blank=True, null=True)#링크
    
    like = models.ManyToManyField(CustomUser, related_name='likes',blank=True)

    def summary(self):
        return self.body[:100]


class Comment(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)
    post = models.ForeignKey(Post, null=True, on_delete=models.CASCADE)
    content = models.TextField(blank=True)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

post/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['category', 'body', 'hashtag', 'image']
        labels = {'category':'카테고리', 'body': '내용', 'hashtag': '해시태그', 'image': '이미지'}

post/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.utils import timezone
from django.http import HttpResponse
import json
from django.core import serializers
from django.core.serializers.json import DjangoJSONEncoder
from .models import Post, Comment
from .forms import PostForm
from account.models import CustomUser
from operator import itemgetter
from django.contrib import messages
from django.db.models import Q

# Create your views here.
def home(request):
    if not request.user.is_authenticated:
        return redirect('login')
    elif not request.user.email_auth:
        return render(request, 'wait_activate.html')

    
    search_keyword = request.GET.get('keyword', '')
    search_type = request.GET.get('type', '')
    # 검색어를 입력했을 경우
    if search_keyword:
        post_list = Post.objects.order_by('-pub_date')
        if len(search_keyword) > 1:
            if search_type == 'all':
                result_list = post_list.filter(Q (body__icontains=search_keyword) | Q (hashtag__icontains=search_keyword) | Q (author__name__icontains=search_keyword)).distinct()
            elif search_type == 'content':
                result_list = post_list.filter(body__icontains=search_keyword)
            elif search_type == 'hashtag':
                result_list = post_list.filter(hashtag__icontains=search_keyword)
            elif search_type == 'author':
                result_list = post_list.filter(author__name__icontains=search_keyword)
            
            return render(request, 'home.html', {'post_list':result_list, 'keyword': search_keyword})
        else:
            messages.error(request, '키워드는 2글자 이상 입력해주세요.')

    # 자신이 팔로우 한 사람들의 최신글 + 최신글을 20개까지 가져오기
    following_list = request.user.followings.all()
    post_list = []
    for following in following_list:
        post_list += list(Post.objects.filter(author = following))
    cnt = len(post_list)
    if cnt < 20:
        all_posts = Post.objects.order_by('-pub_date')
        for post in all_posts:
            if post not in post_list:
                post_list.append(post)
                cnt += 1
            if cnt >= 20:
                break
    else:
        # 최신 20개 글만 가져오기
        post_list.sort(key=itemgetter('pub_date'), reverse=True)
        post_list = post_list[:20]
    
    return render(request, 'home.html', {'post_list':post_list})

def new(request):
    post = PostForm()
    return render(request, 'new.html', {'post':post})

def create(request):
    form = PostForm(request.POST, request.FILES)
    if form.is_valid():
        new_post = form.save(commit=False)
        new_post.pub_date = timezone.now()
        if request.user.is_authenticated:
            new_post.author = request.user
            new_post.save()
            return redirect('detail', new_post.id)
    return redirect('home')

def update(request, id):
    post = get_object_or_404(Post, pk = id)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('detail', post.id)
        else:
            return redirect('home')
    else:
        form = PostForm(instance=post)
        return render(request, 'edit.html', {'post':form,'postmodel':post})

def delete(request, id):
    delete_post = get_object_or_404(Post, pk = id)
    delete_post.delete()
    return redirect('home')

def detail(request, id):
    post = Post.objects.get(id = id)
    comments = Comment.objects.filter(post = id).order_by('pub_date')
    return render(request, 'detail.html', {'post':post, 'comments':comments})

# comment view
def comment_create(request, post_id):
    post = get_object_or_404(Post, pk = post_id)
    writer_id = request.POST.get('writer_id')
    writer = get_object_or_404(CustomUser, pk = writer_id)
    content = request.POST.get('content')
    
    comment = Comment.objects.create(post = post, user = writer, content = content)
    comment.save()
    response = {
        'comment_id': comment.id,
        'writer_profile_image': writer.profile_image.url,
        'writer_name': writer.name,
        'writer_major': writer.major,
        'writer_studentNum': writer.studentNum,
        'content': content,
        'pub_date': comment.pub_date
    }

    return HttpResponse(json.dumps(response, cls=DjangoJSONEncoder), content_type = "application/json")

def comment_delete(request, post_id):
    comment_id = request.POST.get('comment_id')
    delete_comment = Comment.objects.get(pk = comment_id)
    delete_comment.delete()
    response = {
        'message': '성공적으로 삭제되었습니다.'
    }
    return HttpResponse(json.dumps(response, cls=DjangoJSONEncoder), content_type = "application/json")
    return render(request, 'detail.html', {'post':post})

from django.http import HttpResponse,JsonResponse
import json
    
def likes(request): 
    if request.is_ajax(): #ajax 방식일 때 아래 코드 실행
        post_id = request.GET['post_id'] #좋아요를 누른 게시물id (post_id)가지고 오기
        post = Post.objects.get(id=post_id) 
				
        if not request.user.is_authenticated: #버튼을 누른 유저가 비로그인 유저일 때
            message = "로그인을 해주세요" #화면에 띄울 메세지 
            context = {'like_count' : post.like.count(),"message":message}
            return HttpResponse(json.dumps(context), content_type='application/json')

        user = request.user #request.user : 현재 로그인한 유저
        if post.like.filter(id = user.id).exists(): #이미 좋아요를 누른 유저일 때
            post.like.remove(user) #like field에 현재 유저 추가
            message = "좋아요 취소" #화면에 띄울 메세지
        else: #좋아요를 누르지 않은 유저일 때
            post.like.add(user) #like field에 현재 유저 삭제
            message = "좋아요" #화면에 띄울 메세지
        # post.like.count() : 게시물이 받은 좋아요 수  
        context = {'like_count' : post.like.count(),"message":message}
        return HttpResponse(json.dumps(context), content_type='application/json')    

post/templates/detail.html
{% extends 'base.html' %}

{% block content %}
    <head>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
    </head>

    <style>
        .profile-image {
            width: 50px;
            height: 50px;
            object-fit: cover;
        }

        .button {background-color : #5B9BD5; 
                 color: white; 
                 font-size: 13px;
                 border-radius: 5px;
                 padding: 5px 7.5px; 
                 margin: 5px 7.5px;
                 text-align : center;
                 border-style : none;
        }

        h1 {font-size:20px; 
        font-weight:700; 
        padding: 5px 7.6px;
        margin: 5px 7.5px;
        text-align : center;}
    
        #textbox 
        {
            border : 2px solid rgba(91,155,213,0.5);
            padding : 20px 10px 10px 15px;
            border-width:2px;
            border-radius : 6px; 
        }

        #id_body
        {
            font-size : 13px;
            resize :none;
            width : 100%;
            font-family: inherit;
            border : 2px solid rgba(200,200,200,5);
            border-radius : 4px; 
        }

        #id_category
        {
            font-size:12px;
            margin-bottom: 5px;
        }

        .feeling_a {
        background-color: #fff;
        border: 0px;
        color: #5B9BD5;
        font-size:13px;
        float:right;
        margin-left:5px;
        }  
        
        #comment_box {
        background-color: transparent;
        font-size:13px;
        margin-left:5px;
        }     

        .comment_content
        {
            font-size:12px; 
        }

        .noprint
        { display:none; }

        .btn-normal {
            color: white; 
            background-color: #5B9BD5;
            font-size: 5px;
            border-radius: 5px;
            padding: 5px 7.5px; 
            margin: 2px 3px;
            border-style : none;
            text-align: center;
        }
    </style>

     <div class = "container mb-3" id = "textbox">
        <a href="{%url 'home'%}">
        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="#5B9BD5" class="bi bi-arrow-left-square" viewBox="0 0 16 16" style="float:left; margin-right:5px;">
            <path fill-rule="evenodd" d="M15 2a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2zM0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm11.5 5.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/></svg></a>
        <h3 style="float:left">{{post.author.name}}님의 게시물 </h3>
     </div>

    <div class = "container mb-3" id = "textbox">
            <div style="float:left; margin-right:10px"><img class="profile-image" src="{{post.author.profile_image.url}}" alt="프로필 사진"></div> 
            <div style="float:left"><h4>{{post.author.name}}({{post.author.major}}{{post.author.studentNum}})</h4></div>
            <br>
            <br>
            <br>
            <br>
            <div class = "container p-3 mb-3" id = "id_body">
                {% if post.image %}
                <div id="id_image">
                    <img src="{{post.image.url}}" alt="사진" width="130px"height="100px"><br>
                </div>
                {% endif %}
                <br>
                {{post.body|linebreaks}} <br></div>
            <div id="id_category">
            {{post.get_category_display}} <br></div>
            <div id="id_category">
            {{post.hashtag}} <br></div>
           
    
            {% if post.author == user %}
            <a href="{%url 'delete' post.id%}"><button class="btn-normal" style="float:right; margin-left:5px; background-color:red;">삭제</button></a>
            <a href="{%url 'update' post.id%}"><button type="button" class="btn-normal" style="float:right; margin-left:5px;">수정</button></a>
            {% endif %}

            <button id="{{post.id}}" class="feeling_a" onclick="post_like(this.id)">
                {%if request.user in post.like.all%}
                <!-- 로그인 한 유저가 좋아요를 누른 유저일때  -->
                <i id="heart" class="fas fa-heart"></i>
                {%else%}
                <!-- 로그인 한 유저가 좋아요를 누른 유저가 아닐 때  -->
                <i id="heart" class="far fa-heart"></i>
                {%endif%}
                <span id="like_count">{{post.like.count}}</span>
        </button>

        <span style="float:right; font-size:13px;" >{{ post.pub_date|date:'Y-m-d H:i' }}</span>
        </div>

            <div class = "container" id = "textbox">
            {% if user.is_authenticated %}
                <div class="card" id ="comment_box" style="border: 0px;">
                    <div>
                        <div class="col-md-12">
                            {% csrf_token %}
                            <div class="form-group row" style="margin-top:10px;" >
                                <textarea id="comment_content" rows="3" placeholder="댓글을 입력해주세요."></textarea>
                            </div>
                            <div class="text-right" style="right:1px;" id="id_category">
                                <button id="comment_write" class="btn-normal">댓글달기</button>
                            </div>
                        </div>
                        <div id="comment_container">
                            {% if comments %}
                                {% for comment in comments %}
                                <div id='{{ comment.id }}'>
                                    <div>
                                    <img class="profile-image" src="{{comment.user.profile_image.url}}" alt="프로필 사진">
                                    <span style="font-size:13px; font-weight:bold;">{{ comment.user.name }}</span>
                                    <span style="font-size:13px; font-weight:bold;">({{ comment.user.major }} {{ comment.user.studentNum }})</span>
                                    </div>
                                    <span style="float:right">{{ comment.pub_date|date:'Y-m-d H:i' }}</span>
                                    <div class="mt-3">
                                        <div style="white-space:pre-wrap; text-align:left;">{{ comment.content }}</div>
                                        <div style="text-align: right;">
                                        {% if comment.user == user %}
                                            <button class="btn btn-danger" onclick="deleteComment('{{comment.id}}');">삭제</button>
                                        {% endif %}
                                        </div>
                                    </div>
                                    <hr>
                                </div>
                                {% endfor %}
                            {% endif %}
                            <input type="hidden" id="comment_writer_id" value={{user.id}}>
                            <div id="comment_list"></div>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>    

    <script type="text/javascript">
        $(document).ready(function () {
            $('#comment_write').click(function () {
                let content = $('#comment_content').val();
                let writer_id = $('#comment_writer_id').val();
                if (content.length > 0) {
                    createComment(content, writer_id);
                }
                else {
                    alert('댓글을 입력해주세요.');
                }
            })
        })

        function createComment(content, writer_id) {
            $.ajax({
                type: "POST",
                url: "{% url 'comment_create' post.id %}",
                dataType: "json",
                data: {
                    'writer_id': writer_id,
                    'content': content,
                    'csrfmiddlewaretoken': `{{csrf_token}}`,
                },
                success: function (response) {
                    let tempHtml = addComment(response);
                    $('#comment_list').append(tempHtml);
                    $('#comment_content').val("");
                }
            })
        }

        function addComment(response) {
            return `<div id=${response.comment_id}>
                        <div>
                            <img class="profile-image" src="${response.writer_profile_image}" alt="프로필 사진">
                            <span style="font-size:13px; font-weight:bold;">${response.writer_name}</span>
                            <span style="font-size:13px; font-weight:bold;">(${response.writer_major} ${response.writer_studentNum})</span>
                        </div>
                        <span style="float:right">${response.pub_date.substring(0, 10) + ' ' + response.pub_date.substring(11,16)}</span>
                        <div class="mt-3">
                            <div style="white-space:pre-wrap; text-align:left;">${response.content}</div>
                            <div style="text-align: right;">
                            <button class="btn btn-danger" onclick="deleteComment('${response.comment_id}');">삭제</button>
                            </div>
                        </div>
                        <hr>
                    </div>`
        }

        function deleteComment(comment_id) {
            let delete_warning = confirm('댓글을 삭제하시겠습니까?');
            if (delete_warning == true) {
                $.ajax({
                    type: "POST",
                    url: "{% url 'comment_delete' post.id %}",
                    dataType: "json",
                    data: {
                        'comment_id': comment_id,
                        'csrfmiddlewaretoken': `{{csrf_token}}`,
                    },
                    success: function (response) {
                        alert('성공적으로 삭제되었습니다.');
                        window.location.reload();
                    }
                })
            }
        }

        function post_like(id) {
            $.ajax({
                url: "{%url 'likes'%}", // data를 전송할 url 입니다.
                data: {
                    'post_id': id
                }, // post_id 라는 name으로 id 값 전송
                dataType: "json",
                success: function (response) { // ajax 통신이 정상적으로 완료되었을 때
                    $('#like_count').html(response.like_count) //id가 like_count의 내용을 전송받은 좋아요 수로 바꾼다
                    $('#message').html(response.message) //id가 message의 내용을 전송받은 message로 바꾼다
                    $('.toast').fadeIn(400).delay(100).fadeOut(400)
                    if (response.message == "좋아요")
                    //좋아요 눌렀을 때 
                    {
                        $('#heart').attr("class", "fas fa-heart")
                    } else if (response.message == "좋아요 취소")
                    //좋아요 상태에서 다시 눌렀을 때 
                    {
                        $('#heart').attr("class", "far fa-heart")
                    }
                }
            })
        }
    </script>

{% endblock %}

post/templates/edit.html
{% extends 'base.html' %}

{% block content %}

<style>
    .button {
        background-color : #5B9BD5; 
        color: white; 
        font-size: 13px;
        border-radius: 5px;
        padding: 5px 7.5px; 
        margin: 5px 7.5px;
        text-align : center;
        border-style : none;
    }
    h1 {
        font-size:20px; 
        font-weight:700; 
        padding: 5px 7.6px;
        margin: 5px 7.5px;
        text-align : center;
    }

    #textbox 
    {
        border : 2px solid rgba(91,155,213,0.5);
        padding : 20px 10px 10px 15px;
        border-width:2px;
        border-radius : 6px; 
    }
    #id_category
    {
        font-size : 13px;
        font-family: inherit;
        position : relative;
        border : 1px solid rgba(200,200,200,2);
        border-radius : 4px; 
        position:absolute;

          
    }
    #id_category:hover
    {
        border : 2.5px solid rgba(91,155,213,0.5);
        border-radius : 4px; 
        
    }

    #id_body
    {
        font-size : 13px;
        resize :none;
        width : 100%;
        font-family: inherit;
        border : 2px solid rgba(200,200,200,5);
        border-radius : 4px; 
    }

    #id_body:hover
    {
        border : 2.5px solid rgba(91,155,213,0.5);
        border-radius : 4px; 
    }

    
    #id_image
    {
        font-size : 13px;
    }
    #id_image
    {
        font-size : 13px;
        
    }

    #id_hashtag
    {
        font-size : 13px;
        border : 2px solid rgba(200,200,200,5);
        border-radius : 4px; 
        position:absolute;
    }
    #id_hashtag:hover
    {
        border : 2.5px solid rgba(91,155,213,0.5);
        border-radius : 4px;
    }


    .noprint
    { display:none; }
    

</style>

<div class = "container" style="text-align : left; margin-bottom: 50px;">
    <h2 style="text-align: center;"><strong>게시물 수정</strong></h2>
    <br>
    <div id = "textbox">
    <form action="{% url 'update' postmodel.id %}" method="post" enctype="multipart/form-data">
            {%csrf_token%}
            <div class="noprint">
            <input type="{%csrf_token%}" name="csrfmiddlewaretoken" value="JURujI2cQsww7K0BuYgMhmTBx7wIO0TkNhH64FFINvRzoViAfMD37tNWb3OuLju6" ></div>
            <p style="font-size:13px"><label for="id_category">게시글 카테고리&nbsp;&nbsp;&nbsp;&nbsp;</label> <select name="category" id="id_category">
                <option value="management" class='option1'>총무 및 사무</option>
                <option value="business">영업</option>
                <option value="PerDepart">인사</option>
                <option value="customerC">고객상담</option>
                <option value="marketing">마케팅</option>
                <option value="trade">유통 및 무역</option>
                <option value="design">디자인</option>
                <option value="develop" selected>개발</option>
                <option value="judicial">법무 및 특허</option>
                <option value="strategy">전략 및 기획</option>
                <option value="financial">재무 및 회계</option>
                <option value="sales">구매 및 조달</option>
                <option value="service">서비스</option>
                <option value="profession">전문직</option>
                <option value="medical">의료 및 제약</option>
                <option value="educ">교육직</option>
                <option value="construct">건설 및 인테리어</option>
                <option value="research">연구 및 생산, 제조</option>
                <option value="media">미디어</option>
                <option value="etc">특수</option>

    </select></p>

    <p style="font-size:13px"><label for="id_body">내용</label><br>
    {{post.body|linebreaks}}</p>

    <p style="font-size:13px"><label for="id_hashtag">해시태그&nbsp;&nbsp;:&nbsp;&nbsp;</label> {{post.hashtag}}</p>
    <p id="id_image"><label for="id_image">이미지 수정 </label>
    <br>
    {%if postmodel.image %}
    <a href="{{MEDIA_URL}}{{postmodel.image.url}}" id="id_image">{{postmodel.image.name}}</a>
    <input type="checkbox" name="image-clear" id="image-clear_id">
    <p><label for="image-clear_id">이미지 삽입을 취소하려면 체크표를 눌러주세요.</p></label>
    {%endif%}
    <p id="id_image"><label for="id_image">이미지 변경</label> <input type="file" name="image" accept="image/*" id="id_image"></p>
    <div style="text-align: center"><button type="submit" class="button" > 수정하기 </button></div>
    </form>

{% endblock %} 

post/templates/new.html
{% extends 'base.html' %}

{% block content %}

<style>
    .button {background-color : #5B9BD5; 
             color: white; 
             font-size: 13px;
             border-radius: 5px;
             padding: 5px 7.5px; 
             margin: 5px 7.5px;
             text-align : center;
             border-style : none;
    }
    h1 {font-size:20px; 
    font-weight:700; 
    padding: 5px 7.6px;
    margin: 5px 7.5px;
    text-align : center;}

    #textbox 
    {
        border : 2px solid rgba(91,155,213,0.5);
        padding : 20px 10px 10px 15px;
        border-width:2px;
        border-radius : 6px; 

    }
    #id_category
    {
        font-size : 13px;
        font-family: inherit;
        position : relative;
        border : 1px solid rgba(200,200,200,2);
        border-radius : 4px; 
        position:absolute;

          
    }
    #id_category:hover
    {
        border : 2.5px solid rgba(91,155,213,0.5);
        border-radius : 4px; 
        
    }

    #id_body
    {
        font-size : 13px;
        resize :none;
        width : 100%;
        font-family: inherit;
        border : 2px solid rgba(200,200,200,5);
        border-radius : 4px; 
    }

    #id_body:hover
    {
        border : 2.5px solid rgba(91,155,213,0.5);
        border-radius : 4px; 
    }

    
    #id_image
    {
        font-size : 13px;
    }
    #id_image
    {
        font-size : 13px;
        
    }

    #id_hashtag
    {
        font-size : 13px;
        border : 2px solid rgba(200,200,200,5);
        border-radius : 4px; 
        position:absolute;
    }
    #id_hashtag:hover
    {
        border : 2.5px solid rgba(91,155,213,0.5);
        border-radius : 4px;
    }


    .noprint
    { display:none; }
    
    

</style>

<div class = "container" style="text-align : left; margin-bottom: 50px;">
    <h2 style="text-align: center;"><strong>게시물 업로드</strong></h2>
    <br>
    <div id = "textbox">
    <form action="{% url 'create' %}" method="post" enctype="multipart/form-data">
            {%csrf_token%}
            <div class="noprint">
            <input type="{%csrf_token%}" name="csrfmiddlewaretoken" value="JURujI2cQsww7K0BuYgMhmTBx7wIO0TkNhH64FFINvRzoViAfMD37tNWb3OuLju6" ></div>
            <p style="font-size:13px"><label for="id_category">게시글 카테고리&nbsp;&nbsp;&nbsp;&nbsp;</label> <select name="category" id="id_category">
                <option value="management" class='option1'>총무 및 사무</option>
                <option value="business">영업</option>
                <option value="PerDepart">인사</option>
                <option value="customerC">고객상담</option>
                <option value="marketing">마케팅</option>
                <option value="trade">유통 및 무역</option>
                <option value="design">디자인</option>
                <option value="develop" selected>개발</option>
                <option value="judicial">법무 및 특허</option>
                <option value="strategy">전략 및 기획</option>
                <option value="financial">재무 및 회계</option>
                <option value="sales">구매 및 조달</option>
                <option value="service">서비스</option>
                <option value="profession">전문직</option>
                <option value="medical">의료 및 제약</option>
                <option value="educ">교육직</option>
                <option value="construct">건설 및 인테리어</option>
                <option value="research">연구 및 생산, 제조</option>
                <option value="media">미디어</option>
                <option value="etc">특수</option>

    </select></p>

    <p style="font-size:13px"><label for="id_body">내용</label><br> 
    <textarea name="body" rows="10" required id="id_body"></textarea></p>

    <p style="font-size:13px"><label for="id_hashtag">해시태그&nbsp;&nbsp;:&nbsp;&nbsp;</label> <input type="text" name="hashtag" maxlength="50" required id="id_hashtag" placeholder="#을 붙여 입력하세요"></p>

    <p id="id_image"><label for="id_image">이미지 삽입</label> <input type="file" name="image" accept="image/*" id="id_image"></p>
    <div style="text-align: center"><button type="submit" class="button" >게시글 업로드 </button></div>
    </form>
</div>

{% endblock %} 

post/templates/wait_activate.html
{% extends 'base.html' %}

{% block content %}
<style>
	.wrapper {
		margin-top: 40%;
	}
	
	.text {
		font-size: 2rem;
	}

	button {
		color: white; 
        font-size: 5px;
        border-radius: 5px;
        padding: 5px 7.5px; 
        margin: 2px 3px;
        border-style : none;
        background-color: #5B9BD5;
	}
</style>
<div class = "container text-center">
	<br>
	<div class="text mb-3">
		반갑습니다 <strong>{{request.user.name}}</strong>님😎<br>
		서비스 이용을 위해 이메일 인증을 완료해주세요. 감사합니다!!
	</div>
	<a href="{%url 'logout'%}"><button>로그아웃</button></a>
</div>
{% endblock %}